# Generated by Django 4.2.4 on 2023-09-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_relation_item_remove_relation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оцінка')),
                ('in_liked', models.BooleanField(default=False, verbose_name='Обране')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rati', to='products.mainmodel', verbose_name="об'єкт")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': "Зв'язок",
                'verbose_name_plural': "Зв'язок",
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000, verbose_name='Коментарій')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mainmodel', verbose_name='Товар')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.review', verbose_name='parent')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='Оцінка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
