# Generated by Django 4.2.4 on 2023-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Коментарій'),
        ),
        migrations.AddField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.relation', verbose_name='parent'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
