# Generated by Django 4.2.4 on 2023-09-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_relation_comment_relation_created_at_relation_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Оцінка'),
        ),
    ]
