# Generated by Django 4.2.4 on 2023-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_relation_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['-created_at'], 'verbose_name': "Зв'язок", 'verbose_name_plural': "Зв'язок"},
        ),
        migrations.AlterField(
            model_name='relation',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
