# Generated by Django 4.2.4 on 2023-10-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_alter_relation_options_alter_relation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.relation', verbose_name='Відповідь на відгук'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True, verbose_name='Оцінка'),
        ),
    ]
