# Generated by Django 4.2.4 on 2023-10-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0006_alter_relation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.relation', verbose_name='Відповідь на відгук'),
        ),
    ]
