# Generated by Django 4.2.4 on 2023-10-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
