version: '3.7'

services:
  web:
    build: .
    command: gunicorn TOPUS.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

volumes:
  pgdata:
