# Generated by Django 4.2.4 on 2023-10-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_mainmodel_main_image'),
        ('users', '0014_remove_customer_adress_remove_customer_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошик',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='Київ', max_length=100, verbose_name='Місто')),
                ('adress', models.CharField(blank=True, max_length=100, verbose_name='Адресса')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Прийнято', 'Прийнято'), ('Збирається', 'Збирається'), ('Відправлено', 'Відправлено'), ('Готове до видачі', 'Готове до видачі'), ('Відмінено', 'Відмінено')], default='Прийнято', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer', verbose_name='Користувач')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mainmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
