# Generated by Django 4.2.4 on 2023-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_pickup_alter_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.CharField(default='-', max_length=50, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
