# Generated by Django 4.2.4 on 2023-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_pickup_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('-', '-'), ('При отриманні', 'При отриманні'), ('На сайті', 'На сайті')], default='-', max_length=50, verbose_name='Оплата'),
        ),
    ]
