# Generated by Django 4.2.4 on 2023-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='Не вказано', max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('-', '-'), ('При_отриманні', 'При_отриманні'), ('На_сайті', 'На_сайті')], default='-', max_length=50, verbose_name='Оплата'),
        ),
    ]
