# Generated by Django 4.2.4 on 2023-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_city_alter_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.CharField(default='---', max_length=50, verbose_name='Спосіб доставки'),
        ),
    ]
