# Generated by Django 4.2.4 on 2023-11-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay',
        ),
        migrations.AddField(
            model_name='order',
            name='how_to_pay',
            field=models.CharField(choices=[('-', '-'), ('При_отриманні', 'При_отриманні'), ('На_сайті', 'На_сайті')], default='-', max_length=50, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Сплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.SmallIntegerField(default=0, verbose_name='Замовлення: №'),
        ),
        migrations.AddField(
            model_name='order',
            name='summ_of_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Вартість'),
        ),
    ]
