# Generated by Django 4.2.4 on 2023-11-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_pay_order_how_to_pay_order_is_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_order',
        ),
    ]
