# Generated by Django 4.2.4 on 2023-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_item_price_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='how_to_pay',
            field=models.CharField(choices=[('При отриманні', 'При отриманні'), ('На сайті', 'На сайті')], default='-', max_length=50, verbose_name='Спосіб оплати'),
        ),
    ]
