# Generated by Django 4.2.4 on 2023-12-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_remove_order_product_alter_order_summ_of_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='summ_of_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Всього'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
