# Generated by Django 4.2.4 on 2023-09-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Gallery_cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cloth_photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
            },
        ),
        migrations.CreateModel(
            name='Gallery_gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gaming_photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
            },
        ),
        migrations.CreateModel(
            name='Gallery_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вартість')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Бренд')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='main_photo', verbose_name='Фото')),
                ('s_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Знижка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публікація')),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('size', models.CharField(blank=True, choices=[('-', '-'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Розмір')),
                ('season', models.CharField(blank=True, choices=[('ALL_SEASON', 'Все сезон'), ('SUMMER', 'Літо'), ('AUTUM', 'Осінь'), ('WINTER', 'Зима'), ('SPRING', 'Весна')], max_length=11, verbose_name='Сезон')),
                ('department', models.CharField(blank=True, choices=[('Women', 'Жіноче'), ('Men', 'Чоловіче'), ('Unisex', 'Унісекс')], verbose_name='Стать')),
            ],
            options={
                'verbose_name': 'Одяг',
                'verbose_name_plural': 'Одяг',
            },
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='Матеріал')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('color', models.CharField(blank=True, max_length=15, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Ігрова переферія',
                'verbose_name_plural': 'Ігрова переферія',
            },
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('material', models.CharField(blank=True, max_length=50, verbose_name='Матеріал')),
                ('color', models.CharField(blank=True, max_length=15, verbose_name='Колір')),
                ('room_type', models.CharField(blank=True, max_length=50, verbose_name='Для кімнат')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Вага')),
                ('dimensions', models.CharField(blank=True, max_length=30, verbose_name='Розмір')),
            ],
            options={
                'verbose_name': 'Для дому',
                'verbose_name_plural': 'Для дому',
            },
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Оцінка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rati', to='products.mainmodel', verbose_name="об'єкт")),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
    ]
