# Generated by Django 4.2.4 on 2023-08-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вартість')),
                ('brand', models.CharField(max_length=50, null=True, verbose_name='Бренд')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='url')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True, verbose_name='Розмір')),
                ('season', models.CharField(choices=[('SUMMER', 'Summer'), ('AUTUM', 'Autum'), ('WINTER', 'Winter'), ('SPRING', 'Spring')], max_length=6, null=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Публікація')),
            ],
            options={
                'verbose_name': 'Одяг',
                'verbose_name_plural': 'Одягу',
            },
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='Модель')),
                ('color', models.CharField(max_length=15, null=True, verbose_name='Колір')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публікація')),
            ],
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.mainmodel')),
                ('material', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=15, null=True, verbose_name='Колір')),
            ],
            bases=('products.mainmodel',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth', to='products.clothes', verbose_name="об'єкт")),
            ],
            options={
                'verbose_name': 'Руйтинг',
                'verbose_name_plural': 'Рейтинг',
            },
        ),
    ]
