# Generated by Django 4.2.4 on 2023-09-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
