# Generated by Django 4.2.4 on 2023-09-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create', to=settings.AUTH_USER_MODEL, verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='viewed',
            field=models.ManyToManyField(related_name='view', through='products.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery_home',
            name='home_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.home', verbose_name='home_photo'),
        ),
        migrations.AddField(
            model_name='gallery_gaming',
            name='gaming_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.gaming', verbose_name='gaming_photo'),
        ),
        migrations.AddField(
            model_name='gallery_cloth',
            name='clothes_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.clothes', verbose_name='cloth_photo'),
        ),
    ]
