# Generated by Django 4.2.4 on 2023-09-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmodel',
            old_name='S_code',
            new_name='s_code',
        ),
    ]
