# Generated by Django 4.2.4 on 2023-08-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одяг', 'verbose_name_plural': 'Одяг'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(choices=[('ALL_SEASON', 'Все сезон'), ('SUMMER', 'Літо'), ('AUTUM', 'Осінь'), ('WINTER', 'Зима'), ('SPRING', 'Весна')], max_length=11, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('-', '-'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Опис'),
            preserve_default=False,
        ),
    ]
