# Generated by Django 4.2.4 on 2023-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_s_code_mainmodel_s_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-06 17:34', verbose_name='Час створення'),
            preserve_default=False,
        ),
    ]
