# Generated by Django 4.2.4 on 2023-09-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mainmodel_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rati', to='products.mainmodel', verbose_name="об'єкт"),
        ),
    ]
