# Generated by Django 4.2.4 on 2023-10-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одяг', 'verbose_name_plural': 'Одяг'},
        ),
    ]
