# Generated by Django 4.2.4 on 2023-08-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_clothes_options_alter_clothes_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaming',
            options={'verbose_name': 'Ігрова переферія', 'verbose_name_plural': 'Ігрова переферія'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Для дому', 'verbose_name_plural': 'Для дому'},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='gaming',
            name='is_published',
        ),
        migrations.AddField(
            model_name='home',
            name='Room_Type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публікація'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='all_photos', verbose_name='Фото')),
                ('clothes_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.clothes', verbose_name='cloth_photo')),
                ('gaming_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.gaming', verbose_name='gaming_photo')),
                ('home_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.home', verbose_name='home_photo')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
            },
        ),
    ]
