# Generated by Django 4.2.4 on 2023-08-31 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_gaming_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cloth_photos', verbose_name='Фото')),
                ('clothes_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.clothes', verbose_name='cloth_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gaming_photo', verbose_name='Фото')),
                ('gaming_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.gaming', verbose_name='gaming_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='home_photo', verbose_name='Фото')),
                ('home_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.home', verbose_name='home_photo')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
