# Generated by Django 4.2.4 on 2023-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_relation_delete_rating_alter_mainmodel_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['-date_created'], 'verbose_name': 'Одяг', 'verbose_name_plural': 'Одяг'},
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_photo', verbose_name='Головне фото'),
        ),
    ]
