# Generated by Django 4.2.4 on 2023-09-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mainmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='s_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Serial_key'),
        ),
    ]
