# Generated by Django 4.2.4 on 2023-10-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_clothes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_image',
            field=models.ImageField(default='category_photo/no-image-icon.png', upload_to='category_photo', verbose_name='фото'),
        ),
    ]
