# Generated by Django 4.2.4 on 2023-09-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_rating_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Знижка'),
        ),
    ]
