# Generated by Django 4.2.4 on 2023-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_mainmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
