# Generated by Django 4.2.4 on 2023-09-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_clothes_options_alter_mainmodel_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': "Зв'язок", 'verbose_name_plural': "Зв'язок"},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='in_liked',
            field=models.BooleanField(default=False, verbose_name='Обране'),
        ),
    ]
