# Generated by Django 4.2.4 on 2023-09-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_mainmodel_category_alter_mainmodel_s_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категорія'),
        ),
    ]
