# Generated by Django 4.2.4 on 2023-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='main_image',
            field=models.ImageField(default='category_photo/no-image-icon.png', upload_to='main_photo', verbose_name='Головне фото'),
        ),
    ]
