# Generated by Django 4.2.4 on 2023-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_gallery_cloth_gallery_gaming_gallery_home_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_cloth',
            options={'verbose_name': 'Фото товару', 'verbose_name_plural': 'Фото товару'},
        ),
        migrations.AlterModelOptions(
            name='gallery_gaming',
            options={'verbose_name': 'Фото товару', 'verbose_name_plural': 'Фото товару'},
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='main_photo', verbose_name='Фото'),
        ),
    ]
