# Generated by Django 4.2.4 on 2023-09-06 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_mainmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
    ]
