# Generated by Django 4.2.4 on 2023-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_mainmodel_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='dimensions',
            field=models.CharField(blank=True, max_length=30, verbose_name='Розмір(ВхШхГ), см'),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Назва'),
        ),
    ]
