# Generated by Django 4.2.4 on 2023-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_clothes_season_alter_clothes_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_photo', verbose_name='Фото'),
        ),
    ]
