# Generated by Django 4.2.4 on 2023-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_home_dimensions_alter_mainmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='department',
            field=models.CharField(blank=True, choices=[('Жіноча', 'Жіноча'), ('Чоловіча', 'Чоловіча'), ('Унісекс', 'Унісекс')], verbose_name='Стать'),
        ),
    ]
