# Generated by Django 4.2.4 on 2023-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_mainmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
    ]
