# Generated by Django 4.2.4 on 2023-09-22 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_relation_item_remove_relation_user_and_more'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='viewed',
            field=models.ManyToManyField(related_name='view', through='relations.Relation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
