# Generated by Django 4.2.4 on 2023-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_mainmodel_viewed_delete_relation_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='department',
            field=models.CharField(blank=True, choices=[('Жіноче', 'Жіноче'), ('Чоловіче', 'Чоловіче'), ('Унісекс', 'Унісекс')], verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='season',
            field=models.CharField(blank=True, choices=[('Все сезон', 'Все сезон'), ('Літо', 'Літо'), ('Осінь', 'Осінь'), ('Зима', 'Зима'), ('Весна', 'Весна')], max_length=11, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, verbose_name='Розмір'),
        ),
    ]
